# aptly configuration
# Place this at /etc/aptly.conf on the publishing server

{
  "rootDir": "/var/repos/goldfang",
  "downloadConcurrency": 4,
  "downloadPath": "/var/repos/goldfang/downloads",
  "databasePath": "/var/repos/goldfang/db",
  "publicPath": "/var/repos/goldfang/public",
  "serveInAPoint": false,
  "S3PublishEndpoints": {},
  "SwiftPublishEndpoints": {},
  "S3DownloadEndpoints": {},
  "FileSystemPublishEndpoints": {
    "nginx-repo": {
      "rootDir": "/var/www/apt",
      "linkMethod": "copy",
      "verifyMethod": "md5",
      "disableIndexPublishing": false
    }
  }
}
